#%RAML 1.0
title: File API
version: 1.0
baseUri: http://localhost:8081/api

/file:
  /{file_id}:
    get:
      responses: 
        200:
          description: File with requested File ID
          headers:
            Content-type:
                displayName: Content-type
                description: File's MIME type ("application/pdf", etc.)
                type: string
                required: true
          body:
            binary/octet-stream:
              type: file
    delete:
      responses: 
        200:
          body: 
            application/json:
              example:
                { 
                  "status" : "Success",
                  "file_id" : "DCL5K46FS3OIxb5iuKby" 
                }
  post:
    description: Write File
    body: 
      multipart/form-data:
        properties: 
          fileName: 
            description: The name of the file to be uploaded.
            type: file
            fileTypes: ['image/png']
            maxLength: 10485760 # 10 MB = 10485760 Bytes
    responses: 
        200:
          body: 
            application/json:
              example:
                { 
                  "status" : "Success",
                  "file_id" : "DCL5K46FS3OIxb5iuKby" 
                } 